#!/usr/bin/env python3
"""
market-scout report generator
=============================

Turns the scoring engine's results.json (+ the original candidates.json) into a
ready-to-file Obsidian wiki page with proper frontmatter, executive summary,
decision matrix, segment picks, per-candidate cards, and a sources block.

The orchestrator (the LLM) supplies the JUDGMENT prose via --summary / --verdict;
this script handles deterministic structure + the objective matrix so the page is
consistent with the rest of your wiki (matches /ultradeep output style).

Usage
  python3 report.py results.json candidates.json \
      --summary "3-sentence executive summary..." \
      --verdict "The decisive recommendation paragraph..." \
      --out ~/agentic-wiki/research-reports/best-5g-router-2026.md

If --summary/--verdict are omitted, placeholders are emitted for the LLM to fill.
"""

from __future__ import annotations

import argparse
import json
import sys

# reuse the renderer from the scoring engine
sys.path.insert(0, __file__.rsplit("/", 1)[0])
from score import render_md  # noqa: E402


def _load(path):
    with open(path, "r", encoding="utf-8") as fh:
        return json.load(fh)


def _slug(s):
    keep = []
    for ch in s.lower():
        if ch.isalnum():
            keep.append(ch)
        elif ch in " -_/":
            keep.append("-")
    out = "".join(keep)
    while "--" in out:
        out = out.replace("--", "-")
    return out.strip("-")


def build_page(results, candidates, summary, verdict, scout_version="1.0"):
    cand_by_name = {c["name"]: c for c in candidates.get("candidates", [])}
    query = results["query"] or f"best {results['category']}"
    gen = results["generated"]
    slug = _slug(query)

    seg = results["segments"]
    overall = seg.get("best_overall")

    L = []
    # ---- frontmatter (Obsidian) ----
    L += [
        "---",
        "type: research-report",
        f'title: "Market Scout — {query}"',
        f"category: {results['category']}",
        f"updated: {gen}",
        "tags: [market-scout, buying-guide, research-report, "
        f"{results['category']}]",
        "status: evergreen",
        f"profile: {results['profile']}",
        "tool: market-scout",
        f"scout_version: {scout_version}",
        "related:",
        '  - "[[index]]"',
        '  - "[[hot]]"',
        "---",
        "",
        f"# Market Scout — {query.title()}",
        "",
        f"> Generated by the **market-scout** skill ({gen}) · weight profile "
        f"`{results['profile']}` · {len(results['ranking'])} candidates evaluated · "
        f"scoring is deterministic (MCDA engine), prose is judgment.",
        "",
        "## Executive summary",
        "",
        summary or "> [!todo] LLM: write a 3-sentence executive summary here "
                   "(what's best, for whom, the one caveat).",
        "",
        "## The verdict",
        "",
        verdict or "> [!todo] LLM: write the decisive recommendation paragraph here. "
                   "Take a position. Name the buy sequence.",
        "",
    ]

    # ---- decision matrix + segments (deterministic) ----
    L.append(render_md(results))

    # ---- per-candidate cards ----
    L += ["### Candidate cards", ""]
    for i, r in enumerate(results["ranking"], 1):
        c = cand_by_name.get(r["name"], {})
        crown = " 🏆" if r["name"] == overall else ""
        price = f"${r['price_usd']:,.0f}" if r["price_usd"] else "price n/a"
        L.append(f"#### {i}. {r['name']}{crown}")
        meta_bits = [b for b in [r.get("model"), r.get("form_factor"), price] if b]
        L.append(f"*{' · '.join(meta_bits)}*  ")
        L.append(f"**Score {r['score']:.1f}** · value index "
                 f"{('%.0f' % r['value_index']) if r['value_index'] is not None else '—'} · "
                 f"confidence **{r['confidence']}** ({r['n_sources']} sources, "
                 f"{int(r['completeness']*100)}% data complete)")
        L.append("")
        if r.get("note"):
            L.append(r["note"])
            L.append("")
        specs = c.get("metrics", {})
        if specs:
            shown = ", ".join(f"{k} = {v}" for k, v in specs.items() if v is not None)
            L.append(f"> [!info] Specs — {shown}")
            L.append("")
        srcs = c.get("sources", [])
        if srcs:
            L.append("Sources: " + " · ".join(f"[{j+1}]({u})" for j, u in enumerate(srcs)))
            L.append("")

    # ---- methodology ----
    L += [
        "## Methodology",
        "",
        "- **Pipeline:** market-scout 8-phase run (intake → wiki/memory pre-search → "
        "criteria framing → parallel multi-modal research → triangulation + MCDA scoring "
        "→ adversarial red-team → synthesis → wiki filing).",
        f"- **Scoring:** min-max normalized weighted decision matrix, profile `{results['profile']}`. "
        "Missing metrics excluded per-candidate; `completeness` drives the confidence label.",
        "- **Weights used:** " + ", ".join(f"`{k}`={v}" for k, v in results["weights"].items()) + ".",
        "- **Value index:** performance-only score ÷ street price, rescaled 0–100.",
        "- **Confidence:** high = ≥80% data + ≥3 sources; medium = ≥60% + ≥2; else low.",
        "",
        f"_Filed by market-scout v{scout_version}. Re-run: `python3 score.py candidates.json "
        f"--criteria criteria.json --profile {results['profile']}`._",
    ]

    return slug, "\n".join(L) + "\n"


def main(argv=None):
    ap = argparse.ArgumentParser(description="market-scout report generator")
    ap.add_argument("results", help="results.json from score.py")
    ap.add_argument("candidates", help="candidates.json run file")
    ap.add_argument("--summary", default="", help="executive summary prose (LLM-written)")
    ap.add_argument("--verdict", default="", help="verdict paragraph (LLM-written)")
    ap.add_argument("--out", default=None, help="output .md path (default: stdout)")
    args = ap.parse_args(argv)

    results = _load(args.results)
    candidates = _load(args.candidates)
    slug, page = build_page(results, candidates, args.summary, args.verdict)

    if args.out:
        with open(args.out, "w", encoding="utf-8") as fh:
            fh.write(page)
        print(f"[market-scout] wrote {args.out}  (slug: {slug})")
    else:
        sys.stdout.write(page)
    return 0


if __name__ == "__main__":
    sys.exit(main())
